### PR TITLE
major changes to support rhel platform, enterprise edition and tarball installation

### PR DESCRIPTION
**Pull request by vkhatri**
hello! this PR is for below list of changes

- add package install support for `rhel` platform family
- add yum repository resource for `rhel` platform family
- add attributes for `yum/apt` resources
- make `java` setup optional
- add support for `tarball` based installation
- move `configuration` files attributes to `default['neo4j']['config']['...']`
- render `configuration` files attributes instead of managing individual parameters
- add resources for core directory locations
- add `chefignore`
- update `.gitignore` for common patterns
- add support for `enterprise` edition tarball installation
- add support for `enterprise` edition package installation
- make resource attribute `backup` configurable with default value `5`
- define global `user/group` node attributes instead of hardcoding for various resources
- use `node['ipaddress'] instead for config parameter `default['neo4j']['config']['neo4j-server.properties']['org.neo4j.server.webserver.address']`
- fix `ulimit` warning for init.d scripts
- restrict `java` heap size to 32G limit
- add `rake` tasks

### CODE REVIEW

**Comment by vkhatri** [comment]
i will try to work on the rspec once i get some time this sunday.

**Comment by czeeb** [comment]
Hi Virender,

Are these changes ready for me to review?

**Comment by vkhatri** [comment]
@czeeb yes they are!

**Comment by czeeb** [comment]
Virender,

Sorry, this took me so long to go over this pull request.  I really appreciate all the changes you've made!

I hope to deploy version 1.0.0 of this cookbook before the end of next week. There's some other changes I want to make to it before then.

**Pull request merged**
