### PR TITLE
Accept any valid version number

### PR DESCRIPTION
**Pull request by Veraticus**
It would be pretty helpful for those of us with dependencies higher version than these to not be locked to the versions specified in this `metadata.rb`. This allows that.

### CODE REVIEW

**Comment by czeeb** [comment]
Hi Veracticus,

Thanks for the feedback!

The problem with >= is that it assumes that if any of the dependencies had a major version bump that they'd still maintain backwards compatibility in a way that doesn't break this cookbook.  Chances are they will break BC, because that is what semver is about and when you should bump the major version.

I feel your pain on this, I've run into it before as well. I blindly copied the latest versions from each of those modules from supermarket.  Instead of `depends 'apt', '~> 2.7.0'` I should have used `depends 'apt', '~> 2.7'`, which effectively states >= 2.7 and < 3.0.  What I _really_ should do is test older versions of each of the dependencies to find the version that I require to make things work to make the restrictions even easier on people.

If I understand your problem, it is that you are trying to use a dependency that won't resolve? Such as apt 2.8.2 and this cookbook won't allow that?  

```
depends 'apt', '~> 2.7'
depends 'java', '~> 1.31'
depends 'yum', '~> 3.2'
```

The above should do the trick for you?

**Comment by Veraticus** [comment]
Hey Czeeb, that'd work! Thanks for the flexibility. Want me to alter the PR?

**Comment by czeeb** [comment]
Fantastic!  If you could alter the PR I'll see about getting v1.0.4 of the cookbook out later tonight.

**Comment by Veraticus** [comment]
Done! Thanks for your help and for writing the best neo4j cookbook around. :+1:

**Comment by czeeb** [comment]
This has been included with the v1.0.4 released, which I just tagged and pushed to supermarket.  I found a few non-related issues during testing.

**Pull request merged**
